---
- hosts: localhost
  roles:
  - role: offline-prerequisites

- hosts: localhost
  roles:
  - role: configure-client-dns

- hosts: localhost
  roles:
  - role: create-network  

# - hosts: tang-server
#   tasks:
#     - include_role:
#         name: create-tang-key

- hosts: localhost
  roles:
  - role: create-manifests

- hosts: localhost
  roles:
  - role: create-ignition   
  
- hosts: localhost
  roles:
  - role: create-vms
  tags: create-vms

- hosts: localhost
  roles:
  - role: remove-bootstrap

- hosts: localhost
  roles:
  - role: add-workers

# - hosts: localhost
#   roles:
#   - role: approve cert 

- hosts: localhost
  roles:
  - role: deploy-load-balancer
 
# - hosts: localhost
#   roles:
#   - role: wait for install to complete

# - hosts: localhost
#   roles:
#   - role: day 2 operation  
